Repository letsblockit/letsblockit, pull requests merged in 2023-02, with the labels that each got.

#339 youtube-search-cleanup: add new template
  data/filters/templates/youtube-search-cleanup.yaml
Labels: filter-data, new-filter

#340 news: detect template names in changelog and link to page
  go.mod
  go.sum
  nix/letsblockit.nix
  src/filters/repository.go
  src/news/markdown.go
  src/news/releases.go
  src/server/server.go
Labels: backend

#348 youtube-video-title: improve word matching
  data/filters/templates/youtube-video-title.yaml
Labels: filter-data

#353 server: allow setting pgxpool options in envvar
  src/db/store.go
  src/db/test_store.go
  src/server/server.go
Labels: backend

#361 server: serve SVG icons inline to improve loading times
  cmd/utils/extract-icons.go
  cmd/utils/main.go
  data/assets/dist/tabler-sprite-nostroke.svg.gz
  data/data.go
  data/pages/icon.hbs
  data/tabler-icons.yaml
  flake.nix
  scripts/update-assets.sh
  src/assets/.parcelrc
  src/assets/package-lock.json
  src/assets/package.json
  src/pages/pages.go
Labels: backend

#341 Add beta dark mode support
  data/assets/dist/main.css.gz
  data/assets/dist/main.js.gz
  data/pages/_layout.hbs
  data/pages/landing.hbs
  data/pages/list-filters.hbs
  data/pages/user-account.hbs
  data/pages/view-filter.hbs
  src/assets/main.scss
  src/assets/package-lock.json
  src/assets/package.json
  src/db/interface.go
  src/db/migrations/0002_user-preferences.down.sql
  src/db/migrations/0009_colormode.up.sql
  src/db/models.go
  src/db/qUsers.sql.go
  src/db/queries/qUsers.sql
  src/server/helpers.go
  src/server/server.go
  src/server/server_test.go
  src/server/user.go
  src/users/prefs.go
  src/users/prefs_test.go
Labels: frontend

#363 Misceleanous UX improvements
  data/filters/templates/amazon-products.yaml
  data/filters/templates/google-search-cleanup.yaml
  data/filters/templates/linkedin-posts-by-link.yaml
  data/filters/templates/linuxfr-cleanup.yaml
  data/filters/templates/nebula-creators.yaml
  data/filters/templates/search-results.yaml
  data/filters/templates/soundcloud-reposts.yaml
  data/filters/templates/twitter-tweets-by-hashtag.yaml
  data/filters/templates/twitter-tweets-by-user.yaml
  data/filters/templates/url-param-remover.yaml
  data/filters/templates/youtube-channel.yaml
  data/filters/templates/youtube-cleanup.yaml
  data/filters/templates/youtube-mixes.yaml
  data/filters/templates/youtube-recommendations.yaml
  data/filters/templates/youtube-search-cleanup.yaml
  data/filters/templates/youtube-shorts.yaml
  data/filters/templates/youtube-upcoming-videos.yaml
  data/filters/templates/youtube-video-title.yaml
  data/filters/templates/youtube-watched.yaml
  data/pages/list-filters-table.hbs
  go.mod
  go.sum
  nix/letsblockit.nix
  src/filters/repository.go
  src/server/filters_test.go
  src/server/testdata/templates/custom-rules.yaml
Labels: frontend

#368 server: preload github releases on official instances
  src/news/releases.go
  src/server/server.go
Labels: backend
